doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            SharedEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: SharedEntity
            SharedValueObjects:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM/ValueObject'
                prefix: 'App/Shared/Domain\ValueObject'
                alias: SharedValueObject

            OrderEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Database/ORM/Entity'
                prefix: 'App\Order\Domain\Entity'
                alias: OrderEntity
            OrderValueObjects:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Database/ORM/ValueObject'
                prefix: 'App\Order\Domain\ValueObject'
                alias: OrderValueObject

            NotificationEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Notification/Infrastructure/Database/ORM/Entity'
                prefix: 'App\Notification\Domain\Entity'
                alias: OrderEntity
            NotificationValueObjects:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Notification/Infrastructure/Database/ORM/ValueObject'
                prefix: 'App/Notification/Domain\ValueObject'
                alias: OrderValueObject
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
