controllers:
    resource: ../src/Shared/Infrastructure/Http/Controller/
    type: attribute

order:
    resource: ../src/Order/Infrastructure/Http/Controller/
    type: attribute

notification:
    resource: ../src/Notification/Infrastructure/Http/Controller/
    type: attribute
