parameters:
    rabbitmq.host: '%env(RABBIT_HOST)%'
    rabbitmq.port: '%env(int:RABBIT_PORT)%'
    rabbitmq.user: '%env(RABBIT_USER)%'
    rabbitmq.password: '%env(RABBIT_PASSWORD)%'
    rabbitmq.vhost: '%env(default::RABBIT_VHOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Shared/Domain/Entity/'
            - '../src/Shared/Domain/ValueObject/'
            - '../src/Shared/Infrastructure/Kernel.php'
            - '../src/Order/Domain/Entity/'
            - '../src/Order/Domain/ValueObject/'
            - '../src/Notification/Domain/Entity/'
            - '../src/Notification/Domain/ValueObject/'

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Shared\Application\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }
